---
permalink: protect-scsql/task_define_a_clone_strategy_for_sql_server.html 
sidebar: sidebar 
keywords: clone strategy 
summary: クローニング戦略を定義しておくと、それに従ってデータベースのクローニングを実行することができます。 
---
= SQL Server のクローニング戦略を定義する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クローニング戦略を定義しておくと、それに従ってデータベースのクローニングを実行することができます。

. クローニング処理に関する制限事項を確認します。
. 必要なクローンのタイプを決定します。




== クローニング処理の制限事項

データベースをクローニングする前に、クローニング処理の制限事項を確認しておく必要があります。

* 11.2.0.4から12.1.0.1のいずれかのバージョンのOracleを使用している場合、クローニング処理はにあります
_renamedg_commandを実行するとハング状態になります。Oracleパッチ19544733を適用できます
をクリックしてこの問題を修正します。
* ホストに直接接続されたLUNからのデータベースのクローニング（など）
Windowsホスト上のMicrosoft iSCSIイニシエータ）から同じ上のVMDKまたはRDM LUNに接続します
Windowsホスト、または別のWindowsホスト（またはその逆）はサポートされていません。
* ボリュームマウントポイントのルートディレクトリを共有ディレクトリにすることはできません。
* クローンが含まれている LUN を新しいボリュームに移動した場合、そのクローンは削除できません。




== クローニング処理のタイプ

SnapCenter を使用して、 SQL Server データベースのバックアップまたは本番環境のデータベースをクローニングすることができます。

* データベースバックアップからのクローニング
+
クローニングされたデータベースは、新しいアプリケーションを開発する際のベースラインとして機能し、分離に役立ちます
本番環境で発生するアプリケーションエラー。クローニングされたデータベースをにすることもできます
データベースのソフトエラーからのリカバリに使用されます。

* クローンのライフサイクル
+
SnapCenterを使用すると、本番環境との間に定期的なクローンジョブをスケジュール設定できます
データベースがビジーではありません。


