---
permalink: protect-scc/concept_develop_a_plug_in_for_your_application.html 
sidebar: sidebar 
keywords: overview snapcenter 
summary: SnapCenter サーバを使用すると、 SnapCenter へのプラグインとしてアプリケーションを導入および管理できます。 
---
= 概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter サーバを使用すると、 SnapCenter へのプラグインとしてアプリケーションを導入および管理できます。
任意のアプリケーションをSnapCenterサーバに接続して、データを保護できます
管理機能：

SnapCenter では、さまざまなプログラミング言語を使用してカスタムプラグインを開発できます。可能です
Perl、Java、バッチ、またはその他のスクリプト言語を使用してカスタムプラグインを開発します。

SnapCenter でカスタムプラグインを使用するには、次のタスクを実行する必要があります。

* このガイドの手順に従って、使用するアプリケーション用のプラグインを作成します
* 概要ファイルを作成します
* カスタムプラグインをエクスポートして SnapCenter ホストにインストールする
* プラグインの zip ファイルを SnapCenter サーバにアップロードします




== すべての API 呼び出しでの汎用プラグインの処理

すべての API 呼び出しについて、次の情報を使用します。

* プラグインパラメータ
* 終了コード
* エラーメッセージを記録します
* データの整合性




=== プラグインパラメータを使用します

一連のパラメータは、作成されたすべての API 呼び出しの一環としてプラグインに渡されます。次の表に、パラメータの具体的な情報を示します。

|===
| パラメータ | 目的 


 a| 
アクション
 a| 
ワークフロー名を指定します。たとえば、discover、backup、fileOrVolRestore、などです
cloneVolAndLunの略



 a| 
リソース
 a| 
保護対象のリソースが表示されます。リソースは UID とタイプで識別されます。次の形式でプラグインに表示されます。

「 <UID> 、 <type>; <UID> 、 <type> 」のように入力します。例：
インスタンス1、インスタンス、インスタンス2\\DB1、データベース



 a| 
APP_NAME を使用している
 a| 
使用するプラグインを指定します。たとえば、 db2 、 mysql のように指定します。SnapCenter サーバには、リストされているアプリケーションに対するサポートが組み込まれています。このパラメータでは大文字と小文字が区別されます。



 a| 
APP_IGNORE_ERROR
 a| 
（ Y または N ）これにより、アプリケーションエラーが発生した場合、 SnapCenter が終了するか、終了しません。これは、複数のデータベースをバックアップし、単一の障害が発生しないようにする場合に便利です
バックアップ処理を停止します。



 a| 
<resource_name> ____APP_INSTANY_USERNAME
 a| 
SnapCenter クレデンシャルは、リソースに対して設定されます。



 a| 
<resource_name> _APP_INSTANY_PASSWORD
 a| 
SnapCenter クレデンシャルは、リソースに対して設定されます。



 a| 
<resource_name> _<custom_param> です
 a| 
各リソースレベルのカスタムキー値はです
プレフィックスが付いたプラグインで使用できます
「<RESOURCE_NAME>_」を参照してください。たとえば、を指定します
カスタムキーは、リソースの「MASTER_SLAVE」です
「MySQLDB」という名前の場合は、として使用できます
MySQLDB_MASTER_SLAVE

|===


=== 終了コードを使用します

プラグインは、終了コードを使用して処理のステータスをホストに戻します。各
コードには特定の意味があり、プラグインは正しい終了コードを使用して同じことを示します。

次の表に、エラーコードとその意味を示します。

|===
| 終了コード | 目的 


 a| 
0
 a| 
処理に成功しました。



 a| 
99ドル
 a| 
要求された処理はサポートされていないか実装されて



 a| 
100です
 a| 
処理に失敗しました。休止解除をスキップして終了します。デフォルトでは休止解除が実行されます。



 a| 
101です
 a| 
処理に失敗しました。バックアップ処理を続行してください。



 a| 
その他
 a| 
処理に失敗しました。休止解除を実行して終了します。

|===


=== エラーメッセージを記録します

エラーメッセージは、プラグインから SnapCenter サーバーに渡されます。メッセージです
メッセージ、ログレベル、およびタイムスタンプが含まれます。

次の表に、レベルとその目的を示します。

|===
| パラメータ | 目的 


 a| 
情報
 a| 
情報メッセージ



 a| 
警告
 a| 
警告メッセージ



 a| 
エラー
 a| 
エラーメッセージです



 a| 
デバッグ
 a| 
デバッグメッセージ



 a| 
トレース
 a| 
メッセージをトレースします

|===


=== データの整合性を維持

カスタムプラグインでは、同じワークフローの実行操作間でデータが保持されます。の場合
たとえば、休止の終了時にプラグインにデータを格納し、休止解除時にこのデータを使用できます
操作。

保持するデータはプラグインによって Result オブジェクトの一部として設定されます。それが特定のフォーマットに従います
とについては、プラグイン開発の各スタイルで詳しく説明しています。
